version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/var/html/static/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data/

  backend:
    image: sergben/foodgram-backend:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

volumes:
  static_value:
  media_value:
