version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

  db:
    image: postgres
    depends_on:
      - nginx
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data/

  backend:
    image: sergben/foodgram-backend:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./fixtures:/app/fixtures
