version: '3.3'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static/
      - media_value:/app/media/
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data/

  backend:
    build:
      context: ../backend/src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../backend/src/:/app/
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  static_value:
  media_value:
